import fs from 'fs';
import { buildLine } from './builder-utils.js';

const rawLines = [
  {
    id: 'english-anchor-symmetrical-four-knights',
    courseId: 'english-opening',
    subCourseId: 'english-symmetrical',
    name: 'Symmetrical English – Four Knights & The 12. Nxe5 Central Conquest',
    shortName: 'Symmetrical English Anchor',
    category: 'Anchor Mainline',
    eco: 'A33 1. c4 c5 2. Nc3 Nc6 3. Nf3 Nf6 4. g3 d5 5. cxd5 Nxd5 6. Bg2 Nc7',
    pgn: '1. c4 c5 2. Nc3 Nc6 3. Nf3 Nf6 4. g3 d5 5. cxd5 Nxd5 6. Bg2 Nc7 7. O-O e5 8. d3 Be7 9. Nd2 Bd7 10. Nc4 O-O 11. Bxc6 Bxc6 12. Nxe5',
    fullAnnotation: 'The classical foundation of the Symmetrical English. White fianchettoes the light-squared bishop with g3 and Bg2, maneuvers the knight to c4, and executes 11. Bxc6! Bxc6 12. Nxe5!, winning Black\'s key central pawn with a pristine structure.',
    annotations: {
      0: "1. c4 — The English Opening! We control the vital d5 square from the flank without committing central pawns.",
      1: "1... c5 — Symmetrical response. Black mirrors our strategy.",
      2: "2. Nc3 — Increasing grip over d5 and e4.",
      3: "2... Nc6 — Black develops symmetrically.",
      4: "3. Nf3 — Preparing kingside fianchetto and central expansion.",
      5: "3... Nf6 — Four Knights setup.",
      6: "4. g3 — Preparing the hypermodern sniper bishop on g2.",
      7: "4... d5 — Black strikes in the center.",
      8: "5. cxd5 — Flank pawn trades for central pawn.",
      9: "5... Nxd5 — Black recaptures.",
      10: "6. Bg2 — Dominating the long a8-h1 diagonal.",
      11: "6... Nc7 — Black maneuvers knight to reinforce e5.",
      12: "7. O-O — King safety completed.",
      13: "7... e5 — Black constructs the Rubinstein Maroczy-bind structure.",
      14: "8. d3 — Solidifying the center and opening the c1 bishop.",
      15: "8... Be7 — Developing bishop.",
      16: "9. Nd2! — Maneuvering knight to c4, targeting Black's loose e5 pawn.",
      17: "9... Bd7 — Black defends c6.",
      18: "10. Nc4 — Piling up on e5.",
      19: "10... O-O — Black castles.",
      20: "11. Bxc6! — Coach Guidance: The tactical transformation! White eliminates the c6 defender of e5.",
      21: "11... Bxc6 — Black recaptures.",
      22: "12. Nxe5 — White pockets a clean central pawn with a dominating position."
    }
  },
  {
    id: 'english-anchor-four-knights-e5',
    courseId: 'english-opening',
    subCourseId: 'english-symmetrical',
    name: 'Reversed Sicilian – Four Knights 4. g3 & Queenside Expansion (12. axb4)',
    shortName: 'Four Knights e5 Anchor',
    category: 'Anchor Mainline',
    eco: 'A28 1. c4 e5 2. Nc3 Nf6 3. Nf3 Nc6 4. g3 Bb4 5. Bg2 O-O 6. O-O Re8 7. Nd5',
    pgn: '1. c4 e5 2. Nc3 Nf6 3. Nf3 Nc6 4. g3 Bb4 5. Bg2 O-O 6. O-O Re8 7. Nd5 Bc5 8. d3 h6 9. a3 a5 10. Bd2 d6 11. b4 axb4 12. axb4',
    fullAnnotation: 'The Reversed Sicilian (1. c4 e5) allows White to play a Sicilian with an extra tempo! With 7. Nd5, White harasses Black\'s bishop and seizes queenside territory with a3 and b4, capturing the open a-file and commanding the queenside.',
    annotations: {
      0: "1. c4 — English Opening.",
      1: "1... e5 — Reversed Sicilian!",
      2: "2. Nc3 — Controlling d5.",
      3: "2... Nf6 — Developing.",
      4: "3. Nf3 — Attacking e5.",
      5: "3... Nc6 — Defending e5.",
      6: "4. g3 — Fianchetto setup.",
      7: "4... Bb4 — Pinning White's knight.",
      8: "5. Bg2 — Protecting king diagonal.",
      9: "5... O-O — Castling.",
      10: "6. O-O — White castles safely.",
      11: "6... Re8 — Centralizing rook.",
      12: "7. Nd5! — Jumping into the central outpost, hitting the b4 bishop.",
      13: "7... Bc5 — Bishop retreats.",
      14: "8. d3 — Solidifying center.",
      15: "8... h6 — Preventing Bg5.",
      16: "9. a3 — Preparing b4 expansion.",
      17: "9... a5 — Stopping b4.",
      18: "10. Bd2 — Supporting the queenside lever.",
      19: "10... d6 — Solidifying e5.",
      20: "11. b4! — Breaking through on the flank.",
      21: "11... axb4 — Pawn trade.",
      22: "12. axb4 — Coach Guidance: White recaptures, dominating the a-file and driving Black's bishop into passivity."
    }
  },
  {
    id: 'english-punish-reversed-sicilian-d4-fork',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Reversed Sicilian – Punishing 6...Be6?! via 8. d4! & The 13. Rd1 Pin',
    shortName: 'Reversed Sicilian 13. Rd1 Pin',
    category: 'Tactical Punishment',
    eco: 'A29 1. c4 e5 2. Nc3 Nf6 3. Nf3 Nc6 4. g3 d5 5. cxd5 Nxd5 6. Bg2 Be6?! 7. O-O Be7 8. d4!',
    pgn: '1. c4 e5 2. Nc3 Nf6 3. Nf3 Nc6 4. g3 d5 5. cxd5 Nxd5 6. Bg2 Be6 7. O-O Be7 8. d4 exd4 9. Nxd4 Nxd4 10. Qxd4 Bf6 11. Qa4+ c6 12. Nxd5 Bxd5 13. Rd1',
    fullAnnotation: 'A devastating tactical trap in the Reversed Sicilian. Black neglects the long diagonal with 6...Be6?!, and White detonates the center with 8. d4! exd4 9. Nxd4! Nxd4 10. Qxd4 Bf6 11. Qa4+ c6 12. Nxd5 Bxd5 13. Rd1!, winning the pinned bishop on d5!',
    annotations: {
      0: "1. c4 — English.",
      1: "1... e5 — Reversed Sicilian.",
      2: "2. Nc3 — Developing.",
      3: "2... Nf6 — Developing.",
      4: "3. Nf3 — Attack e5.",
      5: "3... Nc6 — Defend.",
      6: "4. g3 — Fianchetto.",
      7: "4... d5 — Black opens center.",
      8: "5. cxd5 — Trade.",
      9: "5... Nxd5 — Recapture.",
      10: "6. Bg2 — Sniper bishop targeting d5.",
      11: "6... Be6?! — Inaccuracy! Neglecting the tactical vulnerabilities on the d-file.",
      12: "7. O-O — Castling.",
      13: "7... Be7 — Developing.",
      14: "8. d4! — Coach Guidance: The central detonation! White strikes at e5 with maximum power.",
      15: "8... exd4 — Black takes.",
      16: "9. Nxd4 — Centralizing with threats on c6 and e6.",
      17: "9... Nxd4 — Black exchanges.",
      18: "10. Qxd4 — Dominating queen centralization.",
      19: "10... Bf6 — Black counter-attacks White's queen.",
      20: "11. Qa4+ — Check! Forcing Black's pawns forward.",
      21: "11... c6 — Black blocks check.",
      22: "12. Nxd5 — Eliminating defender.",
      23: "12... Bxd5 — Black recaptures.",
      24: "13. Rd1! — Tactical Refutation! The absolute pin on the d-file wins Black's bishop on d5 by force."
    }
  },
  {
    id: 'english-punish-reversed-sicilian-6-nb6',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Reversed Sicilian – Punishing 6...Nb6 Inaccuracy via 13. Na4! Squeeze',
    shortName: 'Reversed Sicilian 13. Na4! Squeeze',
    category: 'Tactical Punishment',
    eco: 'A29 1. c4 e5 2. Nc3 Nf6 3. Nf3 Nc6 4. g3 d5 5. cxd5 Nxd5 6. Bg2 Nb6 7. O-O Be7',
    pgn: '1. c4 e5 2. Nc3 Nf6 3. Nf3 Nc6 4. g3 d5 5. cxd5 Nxd5 6. Bg2 Nb6 7. O-O Be7 8. a3 O-O 9. b4 a6 10. d3 Be6 11. Bb2 f5 12. Rc1 Bf6 13. Na4',
    fullAnnotation: 'When Black retreats 6...Nb6, White seizes complete queenside initiative with 8. a3 and 9. b4. With 13. Na4!, White clamps down on the c5 outpost and dominates the queenside.',
    annotations: {
      0: "1. c4 — English.",
      1: "1... e5 — Reversed Sicilian.",
      2: "2. Nc3 — Developing.",
      3: "2... Nf6 — Developing.",
      4: "3. Nf3 — Attacking e5.",
      5: "3... Nc6 — Defending.",
      6: "4. g3 — Fianchetto.",
      7: "4... d5 — Center push.",
      8: "5. cxd5 — Trade.",
      9: "5... Nxd5 — Recapture.",
      10: "6. Bg2 — Attacking knight.",
      11: "6... Nb6 — Passive retreat.",
      12: "7. O-O — Castling.",
      13: "7... Be7 — Developing.",
      14: "8. a3 — Preparing b4.",
      15: "8... O-O — Castling.",
      16: "9. b4 — Expanding queenside.",
      17: "9... a6 — Restricting.",
      18: "10. d3 — Solid center.",
      19: "10... Be6 — Developing.",
      20: "11. Bb2 — Connecting pieces.",
      21: "11... f5 — Overextending.",
      22: "12. Rc1 — Activating rook on c-file.",
      23: "12... Bf6 — Black defends.",
      24: "13. Na4 — Coach Guidance: Conquering the c5 and b6 outposts! White controls all key strategic squares."
    }
  },
  {
    id: 'english-punish-wing-gambit-b5',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Halbutier Wing Gambit Refutation – 1...b5?! & Outside Passed Pawn Squeeze',
    shortName: 'Halbutier 1...b5?! Refutation',
    category: 'Tactical Punishment',
    eco: 'A10 1. c4 b5?! 2. cxb5 a6 3. bxa6 Bxa6 4. Nc3 Nf6 5. Nf3 e6 6. g3 d5 7. d4',
    pgn: '1. c4 b5 2. cxb5 a6 3. bxa6 Bxa6 4. Nc3 Nf6 5. Nf3 e6 6. g3 d5 7. d4 Be7 8. Bg2 O-O 9. O-O Nbd7 10. Bf4 c5 11. Re1',
    fullAnnotation: 'The dubious Jaenisch/Halbutier Wing Gambit (1...b5?!). White calmly accepts the gambit with 2. cxb5 a6 3. bxa6!, retains the extra pawn with clinical development, and leaves Black with zero compensation.',
    annotations: {
      0: "1. c4 — English Opening.",
      1: "1... b5?! — Dubious wing gambit! Black weakens their queenside without gaining central control.",
      2: "2. cxb5! — White takes the free pawn.",
      3: "2... a6 — Black tries to open lines.",
      4: "3. bxa6! — Cleanly taking the second pawn.",
      5: "3... Bxa6 — Black recaptures with bishop.",
      6: "4. Nc3 — Knight development.",
      7: "4... Nf6 — Developing.",
      8: "5. Nf3 — Controlling center.",
      9: "5... e6 — Solidifying.",
      10: "6. g3 — Preparing bishop fianchetto.",
      11: "6... d5 — Black claims center.",
      12: "7. d4! — Staking central control and blunting Black's pieces.",
      13: "7... Be7 — Developing.",
      14: "8. Bg2 — Harmonious development.",
      15: "8... O-O — Castling.",
      16: "9. O-O — Castling.",
      17: "9... Nbd7 — Black mobilizes.",
      18: "10. Bf4 — Active bishop outpost.",
      19: "10... c5 — Black strikes.",
      20: "11. Re1 — Coach Guidance: White is a clean pawn ahead with superior coordination and an easy technical conversion."
    }
  },
  {
    id: 'english-punish-wing-gambit-bb7',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Wing Gambit – 3. e3! & Central Steamroller (10. e4 & 11. Nxd4)',
    shortName: 'Wing Gambit 10. e4 Steamroller',
    category: 'Tactical Punishment',
    eco: 'A10 1. c4 b5 2. cxb5 a6 3. e3 axb5 4. Bxb5 Bb7 5. Nf3 e6 6. O-O Nf6 7. Nc3',
    pgn: '1. c4 b5 2. cxb5 a6 3. e3 axb5 4. Bxb5 Bb7 5. Nf3 e6 6. O-O Nf6 7. Nc3 Be7 8. d4 O-O 9. Re1 c5 10. e4 cxd4 11. Nxd4',
    fullAnnotation: 'A classic positional punishment of flank play. White accepts the pawn, safely blocks Black\'s bishop battery, and seizes the entire center with 8. d4 and 10. e4!, leaving Black completely suffocated.',
    annotations: {
      0: "1. c4 — English.",
      1: "1... b5 — Wing gambit.",
      2: "2. cxb5 — Taking pawn.",
      3: "2... a6 — Line opening attempt.",
      4: "3. e3! — Solidifying and preparing Bxb5.",
      5: "3... axb5 — Black takes.",
      6: "4. Bxb5 — White takes with tempo.",
      7: "4... Bb7 — Black sets up battery.",
      8: "5. Nf3 — Shielding g2 safely.",
      9: "5... e6 — Developing.",
      10: "6. O-O — Castling.",
      11: "6... Nf6 — Developing.",
      12: "7. Nc3 — Developing.",
      13: "7... Be7 — Developing.",
      14: "8. d4 — Claiming center.",
      15: "8... O-O — Castling.",
      16: "9. Re1 — Preparing central expansion.",
      17: "9... c5 — Challenging d4.",
      18: "10. e4! — Coach Guidance: The dual-pawn steamroller! White commands d4 and e4.",
      19: "10... cxd4 — Black trades.",
      20: "11. Nxd4 — White emerges a clean pawn ahead with unchallenged central dominance."
    }
  },
  {
    id: 'english-punish-dutch-setup-f5',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Anglo-Dutch Inaccuracy – 1...f5 & The Decisive 9. Ba3! Trade',
    shortName: 'Anglo-Dutch 9. Ba3! Trade',
    category: 'Tactical Punishment',
    eco: 'A10 1. c4 f5 2. d4 Nf6 3. g3 e6 4. Bg2 d5 5. Nf3 c6 6. O-O Bd6 7. b3 Qe7 8. a4 O-O 9. Ba3',
    pgn: '1. c4 f5 2. d4 Nf6 3. g3 e6 4. Bg2 d5 5. Nf3 c6 6. O-O Bd6 7. b3 Qe7 8. a4 O-O 9. Ba3 Bxa3 10. Nxa3 Nbd7 11. Nc2 Ne4 12. Nce1',
    fullAnnotation: 'Against Black\'s Dutch Stonewall setup (1...f5 and ...d5), White executes the textbook positional strategy: 7. b3 and 9. Ba3!, eliminating Black\'s only active piece (the d6-bishop) and leaving Black with a permanently dead bishop on c8.',
    annotations: {
      0: "1. c4 — English Opening.",
      1: "1... f5 — Anglo-Dutch setup.",
      2: "2. d4 — Claiming the center.",
      3: "2... Nf6 — Developing.",
      4: "3. g3 — Fianchetto.",
      5: "3... e6 — Stonewall preparation.",
      6: "4. Bg2 — Active diagonal control.",
      7: "4... d5 — Locking the center.",
      8: "5. Nf3 — Developing.",
      9: "5... c6 — Building Stonewall wedge.",
      10: "6. O-O — Castling.",
      11: "6... Bd6 — Black's best piece.",
      12: "7. b3 — Preparing Ba3!",
      13: "7... Qe7 — Stopping Ba3 directly.",
      14: "8. a4! — Supporting the Ba3 push.",
      15: "8... O-O — Castling.",
      16: "9. Ba3! — Coach Guidance: The master trade! Swapping off Black's good bishop saddling them with the bad c8 bishop.",
      17: "9... Bxa3 — Black trades.",
      18: "10. Nxa3 — Knight recaptures.",
      19: "10... Nbd7 — Developing.",
      20: "11. Nc2 — Rerouting knight to e5 outpost.",
      21: "11... Ne4 — Black outpost.",
      22: "12. Nce1 — White prepares Nd3 and Ne5, controlling every dark square on the board."
    }
  },
  {
    id: 'english-punish-anglo-dutch-h5-sac',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Anglo-Dutch Refutation – 5. h5! Rook Sacrifice & Royal Execution',
    shortName: 'Anglo-Dutch 6. Rxh5! Sac',
    category: 'Tactical Punishment',
    eco: 'A10 1. c4 f5 2. Nc3 Nf6 3. d4 g6 4. h4 Bg7 5. h5! Nxh5 6. Rxh5! gxh5 7. e4',
    pgn: '1. c4 f5 2. Nc3 Nf6 3. d4 g6 4. h4 Bg7 5. h5 Nxh5 6. Rxh5 gxh5 7. e4 O-O 8. Qxh5 fxe4 9. Nxe4 Qe8 10. Qh4 Nc6 11. Nf3 Qg6 12. Bd3',
    fullAnnotation: 'A stunning tactical thunderbolt! Against Black\'s loose Leningrad Dutch setup, White plays 4. h4! and 5. h5!, detonating Black\'s kingside with the brilliant exchange sacrifice 6. Rxh5! gxh5 7. e4!, ripping open Black\'s unshielded monarch.',
    annotations: {
      0: "1. c4 — English.",
      1: "1... f5 — Dutch.",
      2: "2. Nc3 — Developing.",
      3: "2... Nf6 — Developing.",
      4: "3. d4 — Center.",
      5: "3... g6 — Leningrad setup.",
      6: "4. h4! — The thematic flank storm!",
      7: "4... Bg7 — Developing.",
      8: "5. h5! — Cracking open the h-file.",
      9: "5... Nxh5 — Black grabs pawn.",
      10: "6. Rxh5! — Tactical Refutation! Brilliant exchange sacrifice destroying Black's pawn shelter.",
      11: "6... gxh5 — Forced recapture.",
      12: "7. e4! — Blasting open lines for the queen and bishop.",
      13: "7... O-O — Desperate evacuation.",
      14: "8. Qxh5 — Infiltrating on the kingside.",
      15: "8... fxe4 — Black takes.",
      16: "9. Nxe4 — Recapturing with active threats.",
      17: "9... Qe8 — Challenging queens.",
      18: "10. Qh4 — Maintaining the deadly attack.",
      19: "10... Nc6 — Black attacks d4.",
      20: "11. Nf3 — Developing smoothly.",
      21: "11... Qg6 — Black queen active.",
      22: "12. Bd3 — Coach Guidance: Devastating discovered check threats against Black's king and queen. White is winning."
    }
  },
  {
    id: 'english-punish-keres-defense-c6',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Keres Defense Inaccuracy – 1...e5 2. Nc3 c6 & Queenside Space Strangle',
    shortName: 'Keres Defense 11. b4 Squeeze',
    category: 'Tactical Punishment',
    eco: 'A21 1. c4 e5 2. Nc3 c6 3. Nf3 d6 4. d4 Nd7 5. e4 Ngf6 6. Be2 Be7 7. O-O O-O 8. Qc2 Qc7 9. Rd1 Re8 10. Rb1 Nf8 11. b4',
    pgn: '1. c4 e5 2. Nc3 c6 3. Nf3 d6 4. d4 Nd7 5. e4 Ngf6 6. Be2 Be7 7. O-O O-O 8. Qc2 Qc7 9. Rd1 Re8 10. Rb1 Nf8 11. b4',
    fullAnnotation: 'When Black plays passively with ...c6 and ...Nd7, White seizes central space with d4 and e4, positions rooks on d1 and b1, and launches the crushing 11. b4 queenside expansion, denying Black all counterplay.',
    annotations: {
      0: "1. c4 — English.",
      1: "1... e5 — Center stake.",
      2: "2. Nc3 — Developing.",
      3: "2... c6 — Passive preparation.",
      4: "3. Nf3 — Attacking e5.",
      5: "3... d6 — Defending.",
      6: "4. d4! — Seizing full central space.",
      7: "4... Nd7 — Passive knight.",
      8: "5. e4 — White holds the ideal broad pawn center.",
      9: "5... Ngf6 — Developing.",
      10: "6. Be2 — Solid bishop.",
      11: "6... Be7 — Developing.",
      12: "7. O-O — Castling.",
      13: "7... O-O — Castling.",
      14: "8. Qc2 — Clearing d1 for the rook.",
      15: "8... Qc7 — Queen develops.",
      16: "9. Rd1 — Controlling the central file.",
      17: "9... Re8 — Rook develops.",
      18: "10. Rb1 — Preparing b4 expansion.",
      19: "10... Nf8 — Black maneuvers.",
      20: "11. b4 — Coach Guidance: Flank expansion rolls unopposed. White owns the center and the queenside."
    }
  },
  {
    id: 'english-punish-anglo-slav-qb3',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Anglo-Slav Inaccuracy – 4...Bg4?! & 5. Qb3! Double Attack Refutation',
    shortName: 'Anglo-Slav 5. Qb3! Double Attack',
    category: 'Tactical Punishment',
    eco: 'A11 1. c4 c6 2. Nf3 d5 3. e3 Nf6 4. Nc3 Bg4?! 5. Qb3! Qb6 6. Ne5! Be6 7. d4',
    pgn: '1. c4 c6 2. Nf3 d5 3. e3 Nf6 4. Nc3 Bg4 5. Qb3 Qb6 6. Ne5 Be6 7. d4 Nbd7 8. c5 Qxb3 9. axb3 Nxe5 10. dxe5 Nd7 11. b4',
    fullAnnotation: 'In the Anglo-Slav, developing 4...Bg4?! prematurely weakens b7. White immediately exploits this with 5. Qb3! and 6. Ne5!, gaining tempo, shutting down Black\'s counterplay, and establishing an outside passed pawn fortress on the queenside.',
    annotations: {
      0: "1. c4 — English.",
      1: "1... c6 — Slav setup.",
      2: "2. Nf3 — Developing.",
      3: "2... d5 — Center.",
      4: "3. e3 — Solidifying.",
      5: "3... Nf6 — Developing.",
      6: "4. Nc3 — Developing.",
      7: "4... Bg4?! — Premature bishop venture leaving b7 unprotected.",
      8: "5. Qb3! — Thematic double attack on b7 and d5.",
      9: "5... Qb6 — Defending b7.",
      10: "6. Ne5! — Dominating outpost harassing the bishop.",
      11: "6... Be6 — Bishop retreats.",
      12: "7. d4 — Cementing the center.",
      13: "7... Nbd7 — Challenging e5.",
      14: "8. c5 — Forcing queen trade on favorable terms.",
      15: "8... Qxb3 — Queens traded.",
      16: "9. axb3 — Opening the a-file for White's rook.",
      17: "9... Nxe5 — Black trades.",
      18: "10. dxe5 — Recapturing with space.",
      19: "10... Nd7 — Attacking e5.",
      20: "11. b4 — Coach Guidance: Cementing the queenside pawn chain with an unstoppable queenside pawn majority."
    }
  },
  {
    id: 'english-punish-reversed-dragon-bc5',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Reversed Dragon – Punishing 7...Bc5?! via 8. Nxe5! Fork Trick',
    shortName: 'Reversed Dragon 8. Nxe5! Fork Trick',
    category: 'Tactical Punishment',
    eco: 'A29 1. c4 e5 2. Nc3 Nf6 3. g3 d5 4. cxd5 Nxd5 5. Bg2 Be6 6. Nf3 Nc6 7. O-O Bc5?! 8. Nxe5!',
    pgn: '1. c4 e5 2. Nc3 Nf6 3. g3 d5 4. cxd5 Nxd5 5. Bg2 Be6 6. Nf3 Nc6 7. O-O Bc5 8. Nxe5 Nxe5 9. d4 Nxc3 10. bxc3 Bd6 11. dxe5 Bxe5 12. Bxb7',
    fullAnnotation: 'A classic tactical blunder in the Reversed Dragon. Black plays 7...Bc5?! overlooking the classical center-fork trick 8. Nxe5! Nxe5 9. d4!. White regains the minor piece, pockets a clean pawn, and demolishes Black\'s queenside.',
    annotations: {
      0: "1. c4 — English.",
      1: "1... e5 — Reversed Sicilian.",
      2: "2. Nc3 — Developing.",
      3: "2... Nf6 — Developing.",
      4: "3. g3 — Fianchetto.",
      5: "3... d5 — Center push.",
      6: "4. cxd5 — Trade.",
      7: "4... Nxd5 — Recapture.",
      8: "5. Bg2 — Pressure on d5.",
      9: "5... Be6 — Defending.",
      10: "6. Nf3 — Attacking e5.",
      11: "6... Nc6 — Defending.",
      12: "7. O-O — Castling.",
      13: "7... Bc5?! — Blunder! Overlooking the thematic tactical fork.",
      14: "8. Nxe5! — Tactical Strike! Sacrificing knight temporarily to fork center pieces.",
      15: "8... Nxe5 — Black takes knight.",
      16: "9. d4! — The Fork! Hitting both the c5 bishop and e5 knight simultaneously.",
      17: "9... Nxc3 — Black exchanges.",
      18: "10. bxc3 — Solidifying.",
      19: "10... Bd6 — Bishop retreats.",
      20: "11. dxe5 — Winning piece back.",
      21: "11... Bxe5 — Recapture.",
      22: "12. Bxb7 — Coach Guidance: White snares a clean pawn and controls the open b-file with decisive superiority."
    }
  },
  {
    id: 'english-punish-early-qb6-symmetrical',
    courseId: 'english-opening',
    subCourseId: 'english-tactics',
    name: 'Symmetrical Inaccuracy – Punishing 10...Qa5?! via 11. a3 & 12. b4 Trap',
    shortName: 'Symmetrical 11. a3 & b4 Trap',
    category: 'Tactical Punishment',
    eco: 'A34 1. c4 c5 2. Nc3 Nc6 3. Nf3 g6 4. d4 cxd4 5. Nxd4 Bg7 6. e3 Nf6 7. Be2 O-O 8. O-O d6 9. b3 Bd7 10. Bb2 Qa5 11. a3',
    pgn: '1. c4 c5 2. Nc3 Nc6 3. Nf3 g6 4. d4 cxd4 5. Nxd4 Bg7 6. e3 Nf6 7. Be2 O-O 8. O-O d6 9. b3 Bd7 10. Bb2 Qa5 11. a3',
    fullAnnotation: 'In the Symmetrical English, Black launches a premature queen excursion with 10...Qa5?!. White calmly prepares 11. a3, followed by b4 and Nd5, driving Black\'s queen into traps and conquering the c-file.',
    annotations: {
      0: "1. c4 — English.",
      1: "1... c5 — Symmetrical.",
      2: "2. Nc3 — Developing.",
      3: "2... Nc6 — Developing.",
      4: "3. Nf3 — Developing.",
      5: "3... g6 — Fianchetto.",
      6: "4. d4 — Opening center.",
      7: "4... cxd4 — Trade.",
      8: "5. Nxd4 — Centralize.",
      9: "5... Bg7 — Attacking d4.",
      10: "6. e3 — Solidifying d4.",
      11: "6... Nf6 — Developing.",
      12: "7. Be2 — Solid bishop.",
      13: "7... O-O — Castling.",
      14: "8. O-O — Castling.",
      15: "8... d6 — Solidifying.",
      16: "9. b3 — Fianchettoing dark bishop.",
      17: "9... Bd7 — Developing.",
      18: "10. Bb2 — Connecting pieces.",
      19: "10... Qa5 — Premature queen excursion.",
      20: "11. a3 — Coach Guidance: Preparing b4 to trap Black's queen while securing total queenside dominance."
    }
  }
];

const processed = rawLines.map(buildLine);
const fileContent = `/* ============================================================
   AUTONOMOUSLY CURATED PRACTICAL REPERTOIRE LINES
   Course: english-opening (12 Master Lines - 83% Punishments)
   Tactical Blunder Punishments & Positional Master Refutations
   ============================================================ */

export const englishOpeningLines = ${JSON.stringify(processed, null, 2)};
`;

fs.writeFileSync('src/data/lines/english-opening.js', fileContent, 'utf-8');
console.log(`Successfully built src/data/lines/english-opening.js (${processed.length} lines)`);
